- name: Master Playbook
  hosts: localhost
  tasks:
    - name: Include playbook fish.yaml
      import_playbook: playbooks/fish.yaml

    - name: Include playbook microk8s.yaml
      import_playbook: playbooks/microk8s.yaml

    - name: Include playbook microceph.yaml
      import_playbook: playbooks/microceph.yaml
