- name: Install Helm
  snap:
    name: helm
    classic: yes
    state: present

- name: Check if helm-diff plugin is installed
  command: helm plugin list
  register: helm_plugins
  changed_when: false

- name: Install Helm Diff plugin
  command: helm plugin install https://github.com/databus23/helm-diff
  when: "'diff' not in helm_plugins.stdout"

- name: Install Cert issuer
  kubernetes.core.helm:
    kubeconfig: ./kube-config.yaml
    name: cert-issuer
    chart_repo_url: https://dhis2-sre.github.io/cert-issuer-helm
    chart_ref: cert-issuer
    release_state: present
    namespace: cert-manager
    create_namespace: true
    values:
      email: "{{ cert_manager_email }}"
      server: https://acme-v02.api.letsencrypt.org/directory
      ingressClass: public
