- name: Update apt cache
  apt:
    update_cache: yes

- name: Install snapd
  apt:
    name: snapd
    state: present

- name: Ensure snapd service is started
  systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"
    state: present

- name: Refresh MicroK8s certificates
  command: microk8s refresh-certs -e ca.crt
