- name: Configure Common Firewall rules
  hosts: all
  become: true

  vars:
    ssh_port: 2222

  tasks:
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Set UFW default policies
      ufw:
        state: enabled
        logging: on
        default: "deny"

    - name: Allow SSH
      ufw:
        rule: allow
        port: "{{ ssh_port | int }}"
        proto: tcp

    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS
      ufw:
        rule: allow
        port: 443
        proto: tcp
