- name: Configure Fish
  hosts: all

  vars:
    username: ubuntu

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Fish shell
      apt:
        name: fish
        state: present
      tags: install

    - name: Verify Fish shell path is valid
      stat:
        path: /usr/bin/fish
      register: fish_shell

    - name: Set fish as the default shell
      command: chsh -s /usr/bin/fish "{{ username }}"
      when: fish_shell.stat.exists
      tags: set-default-shell
