- name: Configure Fish
  hosts: all
  tags: install-fish-shell

  vars:
    username: ubuntu

  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes

    - name: Install Fish shell
      become: true
      apt:
        name: fish
        state: present

    - name: Verify Fish shell path is valid
      stat:
        path: /usr/bin/fish
      register: fish_shell

    - name: Set fish as the default shell
      become: true
      command: chsh -s /usr/bin/fish "{{ username }}"
      when: fish_shell.stat.exists
